# Generated by Django 4.0.5 on 2022-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_debt_interest_debt_paymentday_debt_paymentmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='paymentDay',
            field=models.CharField(max_length=20),
        ),
    ]
