# Generated by Django 4.0.5 on 2022-07-14 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_debt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='lPayAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='lPayDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
